services:
  weddingwrangle:
    container_name: weddingwrangle
    image: ghcr.io/willthong/weddingwrangle
    command: gunicorn weddingwrangle.wsgi:application --bind 0.0.0.0:8000 --timeout 600
    volumes:
      - ./app/db.sqlite3:/usr/src/app/db.sqlite3
      - static:/home/app/weddingwrangle/static
    expose:
      - 8000
    ports:
      - 8000:8000

volumes:
  static:
  certs:
  html:
  vhost:
  acme:
