name: CI/CD

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  EMAIL_HOST_USER: willthong@gmail.com
  EMAIL_HOST_PASSWORD: $EMAIL_HOST_PASSWORD
  DEBUG: 0
  SECRET_KEY: $SECRET_KEY
  DJANGO_ALLOWED_HOSTS: wedding.beccy.willthong.com
  VIRTUAL_PORT: 8000
  LETSENCRYPT_HOST: willthong.com
  GHCR_TOKEN: $GHCR_TOKEN

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    outputs:
      image_name: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
        with:
          cosign-release: 'v2.2.4'

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ./app
          file: ./app/Dockerfile.prod
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Copy static files
        run: cp -r ./app/weddingwrangle/static ${{ secrets.weddingwrangle_location }}/static
      - name: Visit Wedding Wrangle directory 
        run: cd ${{ secrets.weddingwrangle_location }}
      - name: Force recreate
        run: docker rm -f weddingwrangle || true
      - name: Make directories
        run: mkdir -p static && mkdir -p app
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Pull container
        run: docker pull ${{ needs.build.outputs.image_name }}
      - name: Start Docker container
        run: |
          docker run -d \
            --name weddingwrangle \
            -p 8000:8000 \
            -v $(pwd)/app/db.sqlite3:/usr/src/app/db.sqlite3 \
            -v $(pwd)/static:/home/app/weddingwrangle/static \
            -e SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            -e EMAIL_HOST_USER="${{ env.EMAIL_HOST_USER }}" \
            -e EMAIL_HOST_PASSWORD="${{ secrets.EMAIL_HOST_PASSWORD }}" \
            -e DJANGO_ALLOWED_HOSTS="${{ env.DJANGO_ALLOWED_HOSTS }}" \
            -e VIRTUAL_PORT=${{ env.VIRTUAL_PORT }} \
            -e LETSENCRYPT_HOST="${{ env.LETSENCRYPT_HOST }}" \
            ghcr.io/willthong/weddingwrangle:master \
            gunicorn weddingwrangle.wsgi:application --bind 0.0.0.0:8000 --timeout 600
      - name: Make migrations
        run: docker exec -t weddingwrangle python manage.py makemigrations
      - name: Migrate database
        run: docker exec -t weddingwrangle python manage.py migrate

